spring:
  application:
    name: ntt-ms-creditcards
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka